export type Point = { x: number; y: number }
export type Personnel = '10' | '11' | '12' | 'empty'
export type FormationId = 'spread' | 'stack' | 'pistol' | 'bunch-left' | 'bunch-right' | 'inline' | 'wing-left' | 'wing-right'
export type FormationOption = { id: FormationId; label: string; description: string }
export type Protection = 'balanced' | 'left' | 'right'
export type ReceiverId = 'X' | 'Z' | 'Y' | 'RB' | 'H'
export type DrawableId = ReceiverId | 'QB'
export type RouteName = 'Slant' | 'Post' | 'Out' | 'Curl' | 'Flat' | 'Wheel' | 'Go' | 'Drag' | 'Comeback' | 'Block'
export type Routes = Record<ReceiverId, Point[]>
export type Receiver = { id: ReceiverId; start: Point; role: string; onLine: boolean }
export type ZoneLandmark = { label: string; x: number; y: number; width: number; height: number; depth: 'deep' | 'underneath' }
export type Defender = { id: string; start: Point; drop: Point; assignment: 'man' | 'zone' | 'rush'; target?: ReceiverId; zone?: ZoneLandmark }
export type Look = { name: string; coverage: 0 | 1 | 2 | 3 | 4 | 6; press: boolean; rushSide: Protection; blitz: number; hint: string; level: number; targetScore: number; front?: string }
export type Engagement = { blocker: string; rusher: string; point: Point }
export type Frame = { time: number; receivers: Record<ReceiverId, Point>; defenders: Record<string, Point>; linemen: Record<string, Point>; engagements: Engagement[]; qb: Point; ball: Point }
export type RunScheme = 'Zone Read' | 'Power' | 'Draw' | 'Counter'
export type PlayKind = 'pass' | 'run'
export type PlayOptions = { formation?: FormationId; qbRoute?: Point[]; kind?: PlayKind; rpo?: boolean; runScheme?: RunScheme; runSide?: 'left' | 'right'; yardsToGoal?: number }
export type ReadDecision = { defender: string; at: number; decision: 'give' | 'pull' | 'keep'; action: 'crash' | 'widen' | 'sit'; text: string; runGain: number; passGain: number }
export type Outcome = 'complete' | 'incomplete' | 'sack' | 'run' | 'qb-run'
export type Simulation = { frames: Frame[]; score: number; won: boolean; target: ReceiverId | null; throwTime: number; catchTime: number; catchPoint: Point; separation: number; yards: number; pocket: number; spacing: number; laneClearance: number; feedback: string[]; gain: number; outcome: Outcome; releasePoint: Point; rollout: 'left' | 'right' | null; anglePenalty: number; read?: ReadDecision; runScheme?: RunScheme }
export type Run = { seed: number; level: number; lives: number; total: number; status: 'playing' | 'over' }
