async page => {
  const failures=[]
  const check=(condition,message)=>{if(!condition)failures.push(message)}
  const errors=[]
  page.on('pageerror',e=>errors.push(e.message))
  page.on('console',m=>{if(m.type()==='error'&&m.text().includes('Maximum update'))errors.push(m.text())})
  await page.setViewportSize({width:1440,height:1000})
  await page.goto('http://127.0.0.1:5173/')
  await page.getByRole('button',{name:'Run play',exact:true}).click()
  await page.waitForTimeout(500)
  check(Number(await page.getByRole('slider',{name:'Play timeline'}).inputValue())>0,'Playback advances')
  await page.getByRole('button',{name:'Pause play',exact:true}).click()
  const paused=await page.getByRole('slider',{name:'Play timeline'}).inputValue()
  await page.waitForTimeout(150)
  check(paused===await page.getByRole('slider',{name:'Play timeline'}).inputValue(),'Pause holds position')
  await page.getByRole('button',{name:'Reset play',exact:true}).click()
  check(await page.getByRole('slider',{name:'Play timeline'}).inputValue()==='0','Reset returns to pre-snap')
  await page.getByRole('combobox',{name:'Defensive coverage'}).selectOption('Cover 3')
  check((await page.locator('.coverage-zone').count())===7,'Cover 3 has three deep and four underneath zones')
  await page.getByRole('checkbox',{name:'Defense',exact:true}).uncheck()
  check(await page.locator('.player.defensive').count()===0,'Defense toggle hides defenders')
  await page.getByRole('checkbox',{name:'Defense',exact:true}).check()
  await page.getByRole('checkbox',{name:'Labels'}).check()
  check(await page.locator('.route-label').count()>0,'Route labels appear')
  await page.getByRole('button',{name:'H: Slot · inside receiver',exact:true}).click()
  check(await page.locator('.assignment-tooltip').isVisible(),'Player assignments open')
  await page.getByRole('button',{name:'Close assignment'}).click()
  await page.getByRole('button',{name:'Zoom in',exact:true}).click()
  check((await page.locator('.zoom-controls').textContent()).includes('110%'),'Zoom changes field')
  await page.getByRole('button',{name:'Reset field view'}).click()
  // PHASE
  const saveButton=page.getByRole('button',{name:'Save to my playbook',exact:true})
  if(await saveButton.count())await saveButton.click()
  await page.reload()
  check(await page.getByRole('button',{name:'Remove from my playbook',exact:true}).count()===1,'Saved concept persists')
  await page.getByRole('button',{name:/My playbook/}).click()
  check(await page.getByRole('heading',{name:'Your playbook.'}).count()===1,'Saved view opens')
  check(await page.locator('.library-card').count()>=1,'Saved view contains lessons')
  await page.getByRole('button',{name:'Field guide',exact:true}).click()
  await page.getByRole('textbox',{name:'Search concepts'}).fill('four verticals')
  check(await page.locator('.library-card').count()===1,'Search filters concepts')
  await page.locator('.library-card-main').click()
  check((await page.locator('h1').textContent()).includes('Four Verticals'),'Selecting search result loads lesson')
  await page.getByRole('button',{name:'Coaching sources 2',exact:true}).click()
  check(await page.locator('.source-list a').count()===2,'Sources expand')
  await page.getByRole('button',{name:'On film',exact:true}).click()
  check(await page.getByRole('dialog').count()===1,'Film dialog opens')
  check((await page.locator('iframe').getAttribute('src')).includes('3emDC2CKOZE'),'Film matches concept')
  await page.getByRole('button',{name:'Close film',exact:true}).click()
  check(await page.getByRole('dialog').count()===0,'Film dialog closes')
  // PHASE
  await page.getByRole('button',{name:'Defense',exact:true}).click()
  await page.getByRole('button',{name:'Cover 2',exact:true}).click()
  check((await page.locator('h1').textContent()).includes('Cover 2'),'Defense lessons select')
  await page.getByRole('button',{name:'On film',exact:true}).click()
  check((await page.locator('iframe').getAttribute('src')).includes('start=431'),'Film uses verified coverage chapter')
  await page.getByRole('button',{name:'Close film',exact:true}).click()
  await page.getByRole('button',{name:'Offense',exact:true}).click()
  await page.getByRole('button',{name:'Route tree 13',exact:true}).click()
  await page.getByRole('button',{name:'2 · Slant',exact:true}).click()
  await page.getByRole('button',{name:'On film',exact:true}).click()
  check((await page.locator('iframe').getAttribute('src')).includes('start=131'),'Film uses verified route chapter')
  await page.getByRole('button',{name:'Official NFL overview',exact:true}).click()
  check((await page.locator('iframe').getAttribute('src')).includes('jxGnX8B8j3g'),'Companion NFL film switches')
  await page.keyboard.press('Escape')
  check(await page.getByRole('dialog').count()===0,'Escape closes dialog')
  // PHASE
  for(const width of [320,375,414,768,1280]){
    await page.setViewportSize({width,height:900})
    await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`No overflow at ${width}px`)
    await page.screenshot({path:`output/playwright/qa-${width}.png`,fullPage:true})
  }
  await page.setViewportSize({width:375,height:812})
  await page.getByRole('button',{name:'Open concept library'}).click()
  check(await page.locator('.sidebar.open').count()===1,'Mobile library opens')
  await page.locator('.mobile-destinations').getByRole('button',{name:/My playbook/}).click()
  check(await page.getByRole('heading',{name:'Your playbook.'}).count()===1,'Mobile saved navigation works')
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.getByRole('button',{name:'GridironDex home'}).click()
  check((await page.locator('h1').textContent()).includes('Mesh'),'Reduced-motion navigation works')
  check(errors.length===0,`No runtime errors: ${errors.join('; ')}`)
  await page.screenshot({path:'output/playwright/final-mobile.png',fullPage:true})
  await page.setViewportSize({width:1440,height:1000})
  await page.screenshot({path:'output/playwright/final-desktop.png',fullPage:true})
  if(failures.length)throw new Error(failures.join('\n'))
  return {passed:true,checks:'Playback, pause/reset, defense and labels, assignments, zoom, persistence, saved view, search, sources, coverage and route film segments, companion film, dialog dismissal, five viewports, mobile navigation, reduced motion',runtimeErrors:errors}
}
