async page=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const check=(condition,message)=>{if(!condition)throw new Error(message)};
 let phase='Home';
 try {
 await page.setViewportSize({width:1440,height:1000});await page.emulateMedia({reducedMotion:'no-preference'});
 await page.goto('http://127.0.0.1:5173/');await page.evaluate(()=>document.fonts.ready);
 check(await page.locator('main button').count()===2,'Home has exactly two choices');
 check(await page.locator('.home-block.offense circle').count()===11,'Offense has eleven O nodes');
 check(await page.locator('.home-block.defense .alignment path').count()===11,'Defense has eleven X nodes');
 check(await page.locator('.sidebar,.library-drawer,.coaching-panel').count()===0,'No previous dashboard');
 await page.getByRole('button',{name:'GridironDex home'}).hover();
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('.wordmark')).color==='rgb(0, 112, 243)');
 await page.getByRole('button',{name:'Offense',exact:true}).hover();
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('.home-block.offense')).backgroundColor==='rgb(230, 228, 223)');
 await page.screenshot({path:'output/playwright/toy-home-hover.png',animations:'disabled'});
 await page.getByRole('button',{name:'Offense',exact:true}).click();
 await page.getByRole('button',{name:'Open routes',exact:true}).waitFor();
 check(await page.locator('.toy-tile').count()===7,'Offense has seven categories');
 await page.getByRole('button',{name:'Open routes',exact:true}).click();
 phase='Routes';await page.getByRole('button',{name:'Select 2 · Slant',exact:true}).waitFor();
 check(await page.locator('.toy-tile').count()===13,'All thirteen routes shown');
 await page.screenshot({path:'output/playwright/toy-routes.png',fullPage:true,animations:'disabled'});
 const slant=page.getByRole('button',{name:'Select 2 · Slant',exact:true});await slant.hover();
 await page.waitForFunction(()=>Number(document.querySelectorAll('.route-glyph')[1].querySelector('.path-ink')?.getAttribute('stroke-dasharray')?.split(' ')[0])>.99);
 await slant.click();check(await slant.getAttribute('aria-pressed')==='true','Click selects route');
 await page.waitForFunction(()=>Number(document.querySelectorAll('.route-glyph')[1].querySelector('.path-ink')?.getAttribute('stroke-dasharray')?.split(' ')[0])>.99);
 await slant.focus();await page.keyboard.press('Enter');
 await page.waitForFunction(()=>Number(document.querySelectorAll('.route-glyph')[1].querySelector('.path-ink')?.getAttribute('stroke-dasharray')?.split(' ')[0])<.9);
 await page.getByRole('button',{name:'Watch 2 · Slant',exact:true}).click();
 phase='Film';await page.getByRole('dialog').waitFor();
 check((await page.locator('iframe').getAttribute('src')).includes('start=131'),'Exact route chapter');
 check(await page.locator('.film-card > *').count()===2,'Film card contains only video and takeaway');
 check(await page.locator('.film-card p').count()===1,'One short coaching takeaway');
 check((await page.locator('.takeaway').textContent()).length<250,'Takeaway is concise');
 check(await page.locator('main').getAttribute('inert')!==null,'Background cannot receive focus');
 await page.screenshot({path:'output/playwright/toy-film.png',animations:'disabled'});
 await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 check(await page.getByRole('button',{name:'Watch 2 · Slant',exact:true}).evaluate(el=>el===document.activeElement),'Film returns focus');
 await page.getByRole('button',{name:'BACK',exact:true}).click();await page.getByRole('button',{name:'Open concepts',exact:true}).click();
 await page.getByRole('button',{name:'Watch Mesh',exact:true}).click();await page.getByRole('dialog').waitFor();
 check((await page.locator('iframe').getAttribute('src')).includes('NJJKbs-eOKw'),'Mesh film');
 check((await page.locator('.takeaway').textContent()).includes('traffic'),'Direct Mesh takeaway');
 await page.getByRole('button',{name:'Close film',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'GridironDex home'}).click();
 await page.getByRole('button',{name:'Defense',exact:true}).click();await page.getByRole('button',{name:'Open coverages',exact:true}).waitFor();
 check(await page.locator('.toy-tile').count()===4,'Defense has four categories');
 await page.getByRole('button',{name:'Open coverages',exact:true}).click();await page.getByRole('button',{name:'Watch Cover 3',exact:true}).waitFor();
 check(await page.locator('.toy-tile').count()===6,'All six coverages');
 const defenderStarts=await page.locator('.toy-tile').evaluateAll(tiles=>tiles.every(tile=>{
  const paths=[...tile.querySelectorAll('.path-guide')];
  const nodes=[...tile.querySelectorAll('.node-x')];
  return paths.length===11 && paths.every((path,index)=>{
   const start=path.getAttribute('d').match(/^M ([\d.]+) ([\d.]+)/);
   const node=nodes[index].getAttribute('d').match(/^M ([\d.]+) ([\d.]+)/);
   return start && node && Number(start[1])===Number(node[1])+13 && Number(start[2])===Number(node[2])+13;
  });
 }));
 check(defenderStarts,'Coverage assignments originate at the eleven X nodes');
 await page.getByRole('button',{name:'Watch Cover 3',exact:true}).hover();
 await page.screenshot({path:'output/playwright/toy-coverages.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Watch Cover 3',exact:true}).click();await page.getByRole('dialog').waitFor();
 check((await page.locator('iframe').getAttribute('src')).includes('start=926'),'Exact coverage chapter');
 await page.getByRole('button',{name:'Close film',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.reload();check(await page.getByRole('heading',{name:'COVERAGES',exact:true}).count()===1,'URL restores section');
 phase='Responsive';
 for(const width of [320,375,414,768]){
  await page.setViewportSize({width,height:900});await page.getByRole('button',{name:'GridironDex home'}).click();await page.getByRole('button',{name:'Offense',exact:true}).waitFor();
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`No horizontal scroll at ${width}`);
  const spills=await page.locator('.home-block-label').evaluateAll(labels=>labels.filter(label=>label.scrollWidth>label.clientWidth+1).length);
  check(spills===0,`Home label fits at ${width}`);
  await page.screenshot({path:`output/playwright/toy-home-${width}.png`,fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Offense',exact:true}).click();await page.getByRole('button',{name:'Open routes',exact:true}).click();await page.getByRole('button',{name:'Select 2 · Slant',exact:true}).waitFor();
  await page.screenshot({path:`output/playwright/toy-routes-${width}.png`,fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Select 2 · Slant',exact:true}).click();
  check(await page.getByRole('button',{name:'Select 2 · Slant',exact:true}).getAttribute('aria-pressed')==='true',`Touch-style selection at ${width}`);
 }
 phase='Reduced motion';await page.emulateMedia({reducedMotion:'reduce'});
 await page.getByRole('button',{name:'Select 1 · Flat',exact:true}).click();
 await page.waitForFunction(()=>Number(document.querySelector('.path-ink').getAttribute('stroke-dasharray').split(' ')[0])>.99);
 await page.getByRole('button',{name:'Watch 1 · Flat',exact:true}).click();await page.getByRole('dialog').waitFor();
 await page.screenshot({path:'output/playwright/toy-film-mobile.png',animations:'disabled'});
 await page.getByRole('button',{name:'Close film',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'GridironDex home'}).click();await page.setViewportSize({width:1440,height:1000});
 await page.mouse.move(1,1);await page.screenshot({path:'output/playwright/toy-final-home.png',animations:'disabled'});
 check(errors.length===0,'No runtime errors: '+errors.join('; '));
 return {passed:true,checks:'Two-choice home, ink hover, 13 routes, selection/redraw, concise film cards, chapters, keyboard dismissal/focus, all coverages, URL restoration, four responsive widths, reduced motion',runtimeErrors:errors};
 }catch(error){throw new Error(`${phase}: ${error.message}`)}
}
