async page => {
  const errors=[]; page.on('pageerror',error=>errors.push(error.message));
  const check=(value,message)=>{if(!value)throw new Error(message)};
  const base='http://127.0.0.1:5173/';
  await page.setViewportSize({width:1440,height:1050});
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.goto(base); await page.evaluate(()=>document.fonts.ready);
  await page.getByRole('button',{name:'Offense',exact:true}).waitFor();
  check(await page.locator('main button').count()===4,'Four home destinations');
  await page.getByRole('button',{name:'GridironDex home'}).hover();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.wordmark')).color==='rgb(0, 112, 243)');
  await page.getByRole('button',{name:'Offense',exact:true}).hover();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.home-block.offense')).backgroundColor==='rgb(230, 228, 223)');
  await page.screenshot({path:'output/playwright/engine-home-desktop.png',animations:'disabled'});
  await page.getByRole('button',{name:'Offense',exact:true}).click();
  await page.getByRole('button',{name:'Open formations',exact:true}).waitFor();
  check(await page.locator('.toy-tile').count()===9,'Nine offense sections');
  await page.getByRole('button',{name:'Open formations',exact:true}).click();
  await page.getByRole('button',{name:'Explore Pistol',exact:true}).waitFor();
  check(await page.locator('.toy-tile').count()===7,'Seven formation diagrams');
  await page.screenshot({path:'output/playwright/engine-formations.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Explore Pistol',exact:true}).click();
  await page.getByRole('dialog').waitFor();
  check(await page.locator('iframe').count()===0,'Diagrams load before video');
  check(await page.locator('main').getAttribute('inert')!==null,'Background is inert');
  const before=await page.locator('.preview-field svg').innerHTML();
  await page.getByRole('button',{name:'Play diagram',exact:true}).click();
  await page.waitForFunction(()=>Number(document.querySelector('input[aria-label="Play progress"]').value)>12);
  await page.getByRole('button',{name:'Pause diagram',exact:true}).click();
  check(await page.locator('.preview-field svg').innerHTML()!==before,'Diagram players move');
  await page.getByRole('slider',{name:'Play progress'}).focus(); await page.keyboard.press('End');
  check(await page.getByRole('slider',{name:'Play progress'}).inputValue()==='100','Diagram scrubs to post-snap');
  await page.getByRole('button',{name:'Reset diagram'}).click();
  check(await page.getByRole('slider',{name:'Play progress'}).inputValue()==='0','Diagram resets');
  await page.getByRole('button',{name:'Film',exact:true}).click();
  check((await page.locator('iframe').getAttribute('src')).includes('start=564'),'Pistol publisher chapter');
  await page.getByRole('button',{name:'Diagram',exact:true}).click();
  await page.keyboard.press('Escape'); await page.getByRole('dialog').waitFor({state:'hidden'});
  check(await page.getByRole('button',{name:'Explore Pistol',exact:true}).evaluate(el=>el===document.activeElement),'Close returns keyboard focus');

  await page.goto(base+'#offense/concepts/mesh');
  await page.getByRole('heading',{name:'Mesh',exact:true}).waitFor();
  await page.locator('.coaching-takeaway').getByRole('link',{name:'Cover 1',exact:true}).click();
  await page.getByRole('heading',{name:'Cover 1',exact:true}).waitFor();
  check(page.url().endsWith('#defense/coverages/cover-1'),'Inline backlink goes to exact diagram');
  check(await page.locator('.preview-field .blueprint-endpoint').count()>0,'Defenders have faded post-snap endpoints');
  await page.getByRole('slider',{name:'Play progress'}).focus(); await page.keyboard.press('End');
  await page.screenshot({path:'output/playwright/engine-cover-1.png',animations:'disabled'});
  await page.goBack(); await page.getByRole('heading',{name:'Mesh',exact:true}).waitFor();
  await page.reload(); await page.getByRole('heading',{name:'Mesh',exact:true}).waitFor();
  await page.getByRole('button',{name:'Close breakdown'}).focus(); await page.keyboard.press('Shift+Tab');
  check(await page.locator('.breakdown-frame').evaluate(el=>el.contains(document.activeElement)),'Modal traps reverse tab');
  await page.keyboard.press('Escape'); await page.getByRole('dialog').waitFor({state:'hidden'});

  const sections=[['offense','routes',13],['offense','concepts',10],['offense','formations',7],['offense','blocking',10],['offense','gaps',4],['offense','personnel',6],['offense','positions',7],['offense','reads',5],['offense','situations',3],['defense','coverages',6],['defense','fronts',6],['defense','stunts',5],['defense','fits',2],['defense','positions',9],['defense','reactions',5],['special','teams',7]];
  const ids=[];
  for(const [side,section,count] of sections){
    await page.goto(base+`#${side}/${section}`);
    await page.getByRole('heading',{name:section==='teams'?'SPECIAL TEAMS':section==='fits'?'RUN FITS':String(section).toUpperCase(),exact:true}).waitFor();
    await page.locator('.concept-blocks .toy-tile').first().waitFor();
    const found=await page.locator('.concept-blocks .toy-tile').evaluateAll(tiles=>tiles.map(t=>t.dataset.concept));
    check(found.length===count,`Expected ${count} lessons in ${side}/${section}, got ${found.length}`);
    ids.push(...found);
    check(await page.locator('.toy-field polygon').count()>0,`${section} has filled arrow caps`);
    check(await page.locator('.toy-field marker').count()===0,`${section} has no overlapping SVG markers`);
  }
  check(ids.length===105&&new Set(ids).size===105,'All 105 unique lessons reachable');
  await page.goto(base+'#defense/stunts/stunt-tex'); await page.getByRole('heading',{name:'Tex',exact:true}).waitFor();
  await page.getByRole('slider',{name:'Play progress'}).focus(); await page.keyboard.press('End');
  await page.screenshot({path:'output/playwright/engine-stunt.png',animations:'disabled'});
  await page.goto(base+'#offense/gaps/gap-b'); await page.getByRole('heading',{name:'B-Gap',exact:true}).waitFor();
  await page.screenshot({path:'output/playwright/engine-gap.png',animations:'disabled'});
  await page.goto(base+'#special/teams/punt-spread'); await page.getByRole('heading',{name:'Spread / shield punt',exact:true}).waitFor();
  await page.screenshot({path:'output/playwright/engine-punt.png',animations:'disabled'});

  for(const width of [320,375,414,768]){
    await page.setViewportSize({width,height:900}); await page.goto(base); await page.getByRole('button',{name:'Offense',exact:true}).waitFor();
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Home fits ${width}`);
    check(await page.locator('.home-block-label').evaluateAll(nodes=>nodes.every(n=>n.scrollWidth<=n.clientWidth+1)),`Block labels fit ${width}`);
    await page.screenshot({path:`output/playwright/engine-home-${width}.png`,fullPage:true,animations:'disabled'});
    await page.getByRole('button',{name:'SPECIAL TEAMS',exact:true}).click(); await page.locator('.concept-blocks .toy-tile').first().waitFor();
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Special teams fits ${width}`);
    await page.screenshot({path:`output/playwright/engine-teams-${width}.png`,fullPage:true,animations:'disabled'});
    await page.getByRole('button',{name:'Explore Punt return wall',exact:true}).click(); await page.getByRole('dialog').waitFor();
    const bounds=await page.locator('.breakdown-frame').boundingBox();
    check(bounds.x>=0&&bounds.x+bounds.width<=width+1,`Breakdown fits ${width}`);
    await page.getByRole('button',{name:'Play diagram',exact:true}).click();
    await page.waitForFunction(()=>Number(document.querySelector('input[aria-label="Play progress"]').value)>0);
    await page.getByRole('button',{name:'Pause diagram',exact:true}).click();
    await page.screenshot({path:`output/playwright/engine-preview-${width}.png`,animations:'disabled'});
    await page.keyboard.press('Escape'); await page.getByRole('dialog').waitFor({state:'hidden'});
  }
  await page.emulateMedia({reducedMotion:'reduce'}); await page.goto(base+'#defense/coverages/cover-3');
  await page.getByRole('button',{name:'Play diagram',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('input[aria-label="Play progress"]').value==='100',{},{timeout:800});
  check(await page.getByRole('slider',{name:'Play progress'}).inputValue()==='100','Reduced motion still exposes final positions');
  await page.getByRole('button',{name:'Close breakdown'}).click(); await page.getByRole('dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'PLAY',exact:true}).click(); await page.getByRole('region',{name:'Tactical Draft game'}).waitFor();
  check(page.url().endsWith('#draft'),'Game accessible from library');
  await page.getByRole('button',{name:'Playbook',exact:true}).click(); await page.getByRole('button',{name:'Offense',exact:true}).waitFor();
  check(errors.length===0,'No app runtime errors: '+errors.join('; '));
  return {passed:true,lessons:ids.length,checks:'Navigation, arrows, inline motion, scrubbing, film chapters, backlinks, focus, 4 responsive widths, reduced motion, game entry',errors};
}
