import assert from 'node:assert/strict'
import { advanceDrive, driveLookSeed, fieldPositionLabel, newDrive } from '../src/game/drive.ts'
import type { Drive } from '../src/game/drive.ts'
import type { Outcome } from '../src/game/model.ts'

const result = (gain: number, outcome: Outcome = 'complete', throwTime = 2.4) => ({ gain, outcome, throwTime })
const start = newDrive(42)
assert.deepEqual(start, { seed: 42, fieldPosition: 25, down: 1, lineToGain: 35, plays: 0, status: 'active', history: [] })

const second = advanceDrive(start, result(4))
assert.equal(second.fieldPosition, 29)
assert.equal(second.down, 2)
assert.equal(second.lineToGain, 35)
const chains = advanceDrive(second, result(6, 'run'))
assert.equal(chains.fieldPosition, 35)
assert.equal(chains.down, 1)
assert.equal(chains.lineToGain, 45)
assert.equal(chains.plays, 2)
assert.deepEqual(chains.history[0], { play: 1, down: 1, start: 25, end: 29, lineToGain: 35, gain: 4, outcome: 'complete', timeToThrow: 2.4 })
assert.equal(start.history.length, 0, 'Progression does not mutate earlier states')
assert.equal(second.history.length, 1, 'History snapshots stay immutable')

const loss = advanceDrive(chains, result(-3, 'run'))
assert.equal(loss.fieldPosition, 32)
assert.equal(loss.lineToGain, 45, 'A loss does not move the line to gain')
assert.equal(loss.down, 2)
const sack = advanceDrive(loss, result(-7, 'sack', 3.1))
assert.equal(sack.fieldPosition, 25)
assert.equal(sack.history.at(-1)?.gain, -7)
assert.equal(sack.down, 3)
const incomplete = advanceDrive(sack, result(20, 'incomplete'))
assert.equal(incomplete.fieldPosition, 25, 'Incomplete pass gains zero even with a stale catch distance')
assert.equal(incomplete.down, 4)
const fourthFailure = advanceDrive(incomplete, result(4, 'qb-run'))
assert.equal(fourthFailure.status, 'turnover')
assert.equal(fourthFailure.down, 4)
assert.equal(fourthFailure.fieldPosition, 29)
assert.equal(fourthFailure.history.length, 6)
assert.strictEqual(advanceDrive(fourthFailure, result(90)), fourthFailure, 'A turnover ends the drive')

const fourthConversion = advanceDrive({ ...newDrive(1), down: 4 }, result(12, 'complete'))
assert.equal(fourthConversion.status, 'active')
assert.equal(fourthConversion.down, 1)
assert.equal(fourthConversion.fieldPosition, 37)
assert.equal(fourthConversion.lineToGain, 47)
const goal = advanceDrive({ ...newDrive(9), fieldPosition: 86, lineToGain: 90, down: 3 }, result(7, 'run'))
assert.equal(goal.fieldPosition, 93)
assert.equal(goal.down, 1)
assert.equal(goal.lineToGain, 100, 'A new series inside the ten is goal-to-go')
const stopped = advanceDrive(goal, result(6, 'qb-run'))
assert.equal(stopped.fieldPosition, 99)
assert.equal(stopped.down, 2)
assert.equal(stopped.lineToGain, 100)
const touchdown = advanceDrive(stopped, result(8, 'run'))
assert.equal(touchdown.status, 'touchdown')
assert.equal(touchdown.fieldPosition, 100)
assert.equal(touchdown.history.at(-1)?.gain, 1, 'Credit only yards to the goal line')
assert.strictEqual(advanceDrive(touchdown, result(-20, 'sack')), touchdown, 'A touchdown ends the drive')
const safety = advanceDrive({ ...newDrive(), fieldPosition: 4, lineToGain: 14 }, result(-8, 'sack'))
assert.equal(safety.status, 'safety')
assert.equal(safety.fieldPosition, 0)
assert.equal(safety.history.at(-1)?.gain, -4)
assert.strictEqual(advanceDrive(safety, result(20)), safety, 'A safety ends the drive')
assert.equal(advanceDrive(newDrive(), result(4, 'sack')).fieldPosition, 25, 'A sack cannot gain yards')
assert.equal(advanceDrive(newDrive(), result(NaN)).fieldPosition, 25, 'Malformed distance never corrupts the drive')

const highScoreFailure = { ...result(0, 'incomplete'), won: true, score: 100 }
assert.equal(advanceDrive(newDrive(), highScoreFailure).down, 2, 'Score and win status do not move chains')
const lowScoreConversion = { ...result(11, 'run'), won: false, score: 0 }
assert.equal(advanceDrive(newDrive(), lowScoreConversion).down, 1, 'Actual gain earns a first down')

assert.equal(fieldPositionLabel(25), 'Own 25')
assert.equal(fieldPositionLabel(55), 'Opp 45')
assert.equal(fieldPositionLabel(50), 'Midfield')
assert.equal(fieldPositionLabel(92.5), 'Opp 7.5')
assert.equal(driveLookSeed(start), driveLookSeed(newDrive(42)), 'Seeded opponents reproduce')
assert.notEqual(driveLookSeed(start), driveLookSeed(second), 'A new play changes the opponent seed')
const seeds = new Set(Array.from({ length: 30 }, (_, plays) => driveLookSeed({ seed: 42, plays })))
assert.equal(seeds.size, 30, 'Consecutive play seeds are distinct')

let march: Drive = newDrive(123)
for (let i = 0; i < 8; i++) march = advanceDrive(march, result(10, i % 2 ? 'complete' : 'run'))
assert.equal(march.status, 'touchdown')
assert.equal(march.plays, 8)
assert.equal(march.fieldPosition, 100)
console.log('Drive checks passed: downs, chains, losses, sacks, incompletions, goal-to-go, touchdown, safety, fourth-down turnover, history, seeded looks and terminal immutability.')
